server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 20000

spring:
  profiles:
    active: ${env-flag} # 默认启动开发环境

springdoc:
  api-docs:
    path: /v3/api-docs
  paths-to-exclude: /actuator/**, /error/**

tiger:
  knife4j:
    enable: true
    setting:
      language: zh_cn
      enable-swagger-models: true
      enable-document-manage: true
      enable-version: true
  mail:
    smtpHost: smtp.mxhichina.com
    smtpPort: 465
    smtpUser:
    smtpPwd:
    senderName: tiger
    smtpSslEnable: true
  log:
    aspect: true
    path: ../logs
  job:
    adminAddresses: http://117.78.51.210:9000/xxl-job-admin
    accessToken: default_token
    appName: ape-frame
    address: xx
    ip: 127.0.0.1
    port: 9999
    logPath: /data/applogs/xxl-job/jobhandler
    logRetentionDays: 30


aliyun:
  oss:
    enabled: true
    accessKeyId: xxx
    accessKeySecret: xxx
    bucketName: xxx
    endpoint: oss-cn-hangzhou.aliyuncs.com

tencent:
  cos:
    enabled: true
    secretId: xxx
    secretKey: xxx
    bucketName: xxx
    region: ap-beijing